### ISSUE TITLE
how to duplicate the speciality ext?

### ISSUE THREAD

**Issue by braguzz** [Ecodev/speciality#2]
How could I duplicate the speciality ext to build another site?

**Comment by braguzz** [comment]
any upgrade to this problem?

**Comment by fabarea** [comment]
I don't know what is your exact situation but what we do - as we have the whole site under git - we include EXT:speciality in the "main" repo.

```
# Remove tracks of git in speciality
cd typo3conf/ext/speciality
rm -rf .git

# Go back to the Document Root
cd -
git add typo3conf/ext/speciality
```

We **duplicate** speciality **for every website** basically. For common configuration between websites we include a script in AdditionalConfiguration.php for custom settings.

**Comment by braguzz** [comment]
su you duplicate the folder 'speciality' and every content inside all files
inside speciality folder that link to folder?

f.e if I rename to speciality1 I have to rename
Configuration\TsConfig\Page\config.ts
and in line 1 modify to
<INCLUDE_TYPOSCRIPT:
source="FILE:EXT:speciality1/Configuration/TsConfig/Page/rte.ts">

and so on?




2015-04-16 13:20 GMT+02:00 Fabien Udriot <notifications@github.com>:

**Comment by braguzz** [comment]
yes it works thanks

2015-04-16 13:35 GMT+02:00 Paolo Bragagni <paolo.bragagni@gmail.com>:

**Comment by fabarea** [comment]
ok, nice

(we don't duplicate speciality -> speciality1 as mentioned above)

**Comment by braguzz** [comment]
don't duplicate as mentioned above?

so I dont understand...
arghhh

2015-04-16 14:32 GMT+02:00 Fabien Udriot <notifications@github.com>:

**Comment by fabarea** [comment]
We don't duplicate it terms of copying the files. We just start it from where it is and kind of **fork** (we never update the code back from master, except edge cases). That's how to take "duplicate".

**Comment by braguzz** [comment]
I got it

2015-04-16 15:14 GMT+02:00 Fabien Udriot <notifications@github.com>:

**Comment by braguzz** [comment]
I dont got it! ;)
I mean... I have two speciality for two sites, but in every page layout I have the layouts of the two speciality.

I'd like to have layout1 for the site with sapeciality1 and
Layout2 with the site with specialitry2

I miss something...
