### ISSUE TITLE
howto migrate speciality to TYPO3 6.2.5

### ISSUE THREAD

**Issue by gilas1959** [Ecodev/speciality#3]
Hi
thank you for your great work. All works fine under T3 6.1.x.
Today I attempted to run a new site (as testing site) then I installed a fresh TYPO3 6.2.5 installation.
After creating some users (_cli_lowlevel _cli_scheduler) I installed this extensions, following this order:

fluidcontent 4.1.0
flux 7.1.0
vhs 2.0.2
fluidcontent_bootstrap 3.0.0
vidi 0.2.0
media management 3.1.0

Then I've  configured "media management" and  I uploaded 'speciality' from another site.

The result is that some things are changed from vhs 2.0, so I can't run previous code ie:
"<v:var" now is "<v:v ariable"
nothing works and then I can't find anywehere some doc to migrate my templates from 1.x to 2.0.2.

ok then I switched to vhs 1.9.6 and now the result is that error:

Could not analyse class:TYPO3\CMS\Media\ViewHelpers\Widget\CarouselViewHelper maybe not loaded or no autoloader?

I can see correctly from my BE (page properties), ie. the layouts to select through speciality but the BE still shows 4 columns as the blank installation of TYPO3. No way to have the fluid columns.

Now I'm in doubt.... there is a way to migrate fluidcontent, etc. from 6.1.11 to 6.2.5?

thank you for your help

**Comment by pharmaline** [comment]
Hi gilas1959,

i got the same Error. Do you have a solution for this problem?

**Comment by gilas1959** [comment]
Hi
   thank your for your message.
   Unfortunately the author of speciality answers very slow to our issue.
   I tried to install new "speciality distributon" but recently the develops seems to be very slow.
   So I decided to run the new sites using exclusively the Introduction Official distribution.
   Howevere there are 2 sites that I want migrate since 6.1 to 6.2.
   If you are interested we can keep in touch, please tell me what do you want to do.
   cordially
   ALEX

   From "Christian Platt" notifications@github.com

   To "Ecodev/speciality" speciality@noreply.github.com

   Cc "gilas1959" at@specialistaweb.it

   Date Wed, 18 Feb 2015 01:59:10 -0800

   Subject Re: [speciality] howto migrate speciality to TYPO3 6.2.5 (#3)

**Comment by pharmaline** [comment]
Hi,

i quite, cause there are a lot of Namespace Errors. I think speciality needs more fixes than it takes time to setup the Site in  a clean T3 6.2 Installation with Distributorpackage.
bernd

**Comment by PowerKiKi** [comment]
Hey, @fabarea could you chime in and clarify the situation here, please ? I believe we use this on 6.2 as well, so there should be a way to make it work, right ?

**Comment by fabarea** [comment]
Yes, current version is built around 6.2. I have just updated the extensions references yesterday. To install a fresh copy, the advised way is to use Composer. It could be a TER release in the future but it needs a bit of polish. 

<pre>
composer create-project ecodev/typo3-cms-speciality-distribution SpecialityDistribution 
@see refer to the tutorial at the top of https://github.com/Ecodev/typo3-cms-speciality-distribution
</pre>

To migrate from 6.1 to 6.2, you should:

* Upgrade all extensions (there should be all 6.2 with the time)
* Upgrade the Core to latest LTS
* Run the migration wizard from the Install Tool
* Fix all the rest... (sorry no magic receipt here!)

Some of the FluidTYPO3 syntax has changed along the way, more particularly about Flux. I am attaching a little Gist, I successfully used to upgrade the internal syntax. Here [we go](https://gist.github.com/fabarea/aaa973dcf15b7485fd49). Also I recommend skimming the blog articles from https://fluidtypo3.org/blog.html and see for other changes that have occurred. Hope this help.

**Comment by gilas1959** [comment]
Hi I think this is a great work.
Unfortunately I can't understand what do you mean for "Fix all the rest..."; the work to compare old a newer files is a bit complex and tedious. I hope you have on mind to do a migration tool (ie. a pure php program to do  it). To do it manually seems to be really a crazy work.
thank you.

**Comment by fabarea** [comment]
[The Gist](https://gist.github.com/fabarea/aaa973dcf15b7485fd49) should help as pointed out.
