### ISSUE TITLE
Navigation Is not working 

### ISSUE THREAD

**Issue by wabajwa** [Ecodev/speciality#57]
I have installed the `TYPO3 7.6.15 LTS` via composer. and also i have installed the speciality and speciality distribution packages. As, far i have no log errors now, and i have also my front end after activating the speciality package. 
![nav](https://cloud.githubusercontent.com/assets/24478656/23263342/422e4d72-f9de-11e6-97e5-22b90bb8e320.JPG)
This is how it looks now, but the issue is that its navigation menu is not working, if i click on any of them for example, About typo3, or guides or any other, the page doesn't change, it remains still here. 
Moreover, i can see these by adding their id's in the URL. I don't know where is the issue now. If any one has idea please help. Thanks

**Comment by fabarea** [comment]
Could be a problem with RealURL. I would deactivate the extension and see what I get as URL.
