### ISSUE TITLE
<v:page.menu> do not display shortcut's subpages

### ISSUE THREAD

**Issue by kaolol** [Ecodev/speciality#6]
This menu http://bit.ly/1Fjgv05 line 12 do not display shortcut's subpages. Is it normal ? Any way to fix it ? 
Should I post this here or on VHS  github ?
All the best,
Laurent

**Comment by fabarea** [comment]
I think it should be configured likewise:
https://github.com/Ecodev/speciality/blob/master/Resources/Private/Partials/Navigation.html#L31

In the context of the footer partial:
```
<f:if condition="{menuPage.nav_title} != '' ">
	<f:then>{menuPage.nav_title}</f:then>
	<f:else>{menuPage.title}</f:else>
</f:if>
```
-> same would apply to the sub-pages.

If you can make a PR after testing that would be nice from you.

**Comment by kaolol** [comment]
Hi ! Thank you for your reply.

But I don't understand ;)
I do not try to display nav_title..

I try to display subpages of page of type "shortcut".
Or did I misunderstood something ?
All the best
Laurent

**Comment by fabarea** [comment]
Ah right. I read too quickly. ;)

I wonder if there is something to play with attribute `doktype` or `useShortcut*`
https://fluidtypo3.org/viewhelpers/vhs/master/Page/MenuViewHelper.html

**Comment by kaolol** [comment]
Be sure I've checked the doc before ! ;)
doktype do not change anything, the shortcuts are displayed in the menu ;)
But subpages of shortcuts do not...

useShortcutTarget 	Optional param for using shortcut target instead of shortcut itself for current link
useShortcutUid 	If TRUE, substitutes the link UID of a shortcut with the target page UID
Not helping much... I've tested anyway but do not affect behviour for subpages...

Do you think it could be a bug ?
By the way, great thanks for your help, it is really cool not to be alone with that issue ;)

**Comment by kaolol** [comment]
IT cool be  
excludeSubpageTypes
that is set by defaut

Il found this 
`<addr> <xsd:attribute type="xsd:mixed" name="excludeSubpageTypes"
default="'SYSFOLDER'" php:type="mixed">
in
`<addr> ./vhs/Resources/Private/Schemas/Vhs.xsd:17723

**Comment by kaolol** [comment]
Ok, it, just update to the lastest version of VHS version from github and it look ok.
I hope you don't hate me too much !

**Comment by fabarea** [comment]
no problem!
