### ISSUE TITLE
when for T3 7?

### ISSUE THREAD

**Issue by braguzz** [Ecodev/speciality#7]
Does the ext works with t3 7?

thanks in advance,
Paolo

**Comment by fabarea** [comment]
It should for biggest part what it concerns TYPO3Fluid extensions. What is not fully operational is the list module Vidi but perhaps you don't need that.

**Comment by braguzz** [comment]
I'm trying to set it up, but, for example, when I create new page content of type  'Regular Text element', I get an 'empty page' (the same if I edit an already present text CE)...

**Comment by fabarea** [comment]
What exact version of CMS 7.x (they just released 7.2 a few hours ago, it is still hot :) )?

**Comment by braguzz** [comment]
7.1

argghhh


2015-04-28 15:00 GMT+02:00 Fabien Udriot <notifications@github.com>:

**Comment by braguzz** [comment]
better with 7.2, but RTE tell me that 'The editor is being loaded. please wait...' but it never loads

**Comment by braguzz** [comment]
![image](https://cloud.githubusercontent.com/assets/5434803/7373449/d2a9b4d8-edcc-11e4-99cb-f6507d4346f1.png)

**Comment by braguzz** [comment]
if I remove speciality rte page configuration, RTE loads
